### PR TITLE
Fix to the crash when selecting Custom batlle

### PR DESCRIPTION
**Pull request by Manpapper**

### CODE REVIEW

**Comment by Manpapper** [comment]
I just updated it for version 1.7.2 of bannerlord can you update it on nexus ?
If you can't, Can you grant me access to nexus for this mod so I can update it ?

**Comment by capdecarles** [comment]
Hi Manpapper, I've granted permissions to you on Nexus to upload the file as requested and I'm approving this PR. 

Sorry about the delay, I've been away for some time. Thanks for your contribution! :)

**Comment by Manpapper** [comment]
Thanks :)

**Comment by Manpapper** [comment]
I just update new version on nexus

**Pull request merged**
