### PR TITLE
Update for 1.7.0

### PR DESCRIPTION
**Pull request by Manpapper**
party.isLeaderLess no longer exist
party.IsMainParty is enough to recognize hero party

### CODE REVIEW

**Comment by Manpapper** [comment]
image

**Comment by Manpapper** [comment]
You will have to add MCMv4.dll in the folder:
image

**Comment by capdecarles** [comment]
Hey man, thanks a lot for the contribution, looks good :D

I put the MCMv4.dll in the folder as you posted, but got some errors during compilation which seem related to MCMv4.dll dependencies:
image
I tried to add it as a reference, also added the .dll's from ButterLib, UIExtender and Harmony as they're listed as dependencies for MCM, but no luck.

I'm a bit rusty on the .Net side, do you maybe have a hint on this?

**Comment by Manpapper** [comment]
I only have those dll as reference:
image

**Comment by Manpapper** [comment]
I just pushed my visual studio config maybe it will help you

**Comment by Manpapper** [comment]
The file TrainTroops.props contains variable which are use as parameters in TrainTroops.csproj
So if bannerlord isn't in this folder for you, you will have to change it's value in the props file

**Comment by Manpapper** [comment]
I didn't upload my TrainTroops.csproj file since it only contains debugging parameters.

**Comment by capdecarles** [comment]
Got it to run :D thanks!! I'll maybe add an setting so AI can also train and upload the new changes.

**Pull request merged**
